### ISSUE TITLE
Suggestion: Rename Environment to Context

### ISSUE THREAD

**Issue by adaliszk** [suned/serum#13]
The different environment usually referred as Containers in IoC frameworks, it makes more sense because it's more generic. You could have different reasons to separate something than just Environments.

**Comment by suned** [comment]
Definitely many other DI frameworks use the term "Container", but I've always felt that this was a bad name (basically too generic 😀 ), and didn't really communicate what you would use it for. But maybe `Environment` is not better. I was also considering `Configuration` or simply `Context`.

**Comment by adaliszk** [comment]
Context is even better, the thing is that while usually huge applications only differentiate Environments a proper SOLID application has Contexts for each module and sometimes the Context changes depending on the given task.

**Comment by suned** [comment]
I'm up for changing environment to context! :)

**Comment by adaliszk** [comment]
Okay, now I'm occupied with the unit test refactoring after that I could open a PR for it.

**Comment by suned** [comment]
You're more than welcome, otherwise I don't mind either :)

**Comment by suned** [comment]
Fixed in https://github.com/suned/serum/commit/a1acbc68ea77b6942d7d8ffcd4fc48a92c41255b but pending release.

**Comment by suned** [comment]
Fixed in https://pypi.org/project/serum/5.0.0/
