### ISSUE TITLE
Use GitLab for CI/CD

### ISSUE THREAD

**Issue by adaliszk** [suned/serum#19]
I know that the project uses Circle-CI right now, but it would make sense to move the code and the main development into GitLab because you can use the built-in CI/CD with docker and you can even serve your docker image for those who want to mess with this library/micro-framework ;-)

**Comment by suned** [comment]
Having a docker image would be nice, but since the dependencies for this project are extremely limited, I don't think changing CI to have better docker image support is really worth the effort. I really like the ease of CIrcleCI. Closing this for now
