### ISSUE TITLE
Don't load IPython automatically

### ISSUE THREAD

**Issue by adaliszk** [suned/serum#23]
It would be nice if the library doesn't do anything until you don't explicitly say so. Having the IPython right in the `__init__.py` feels wrong, I think it would make sense to extract that and use it in a separate file which can be loaded when it's actually necessary.

**Comment by suned** [comment]
Sounds good, I'm not sure how to actually integrate it with ipython though. Maybe you can put it in an file called `ipython_extension.py` and then instruct users to add `serum.ipython_extension` to their ipython config. Not sure if ipython supports that though, would have to investigate.

**Comment by suned** [comment]
After more consideration, I'm not sure I see the harm in the current implentation. Imo just having to add `serum` to your ipython config is more clean.
