### ISSUE TITLE
Singleton not working without any context

### ISSUE THREAD

**Issue by nachtmaar** [suned/serum#24]
Singleton injection does not work, when no Context() created previously.

The following example shows the error:
- calling `broken_if_no_context_used()` shows the error
- if calling `works()` beforehand, calling `broken_if_no_context_used()` works too

We should add a unit test for this.

```python
from serum import singleton, inject, Context


@singleton
class ExpensiveObject:
    pass


@inject
class NeedsExpensiveObject:
    expensive_instance: ExpensiveObject


def works():
    with Context():
        instance1 = NeedsExpensiveObject()
        instance2 = NeedsExpensiveObject()
        assert instance1.expensive_instance is instance2.expensive_instance
        print('context works')


def broken_if_no_context_used():
    # works if works() called previously
    instance1 = NeedsExpensiveObject()
    instance2 = NeedsExpensiveObject()
    assert instance1.expensive_instance is instance2.expensive_instance
    print('without context works')


# works()
broken_if_no_context_used()
```

Error:
```python
Traceback (most recent call last):
  File "dij2.py", line 33, in <module>
    broken_if_no_context_used()
  File "dij2.py", line 28, in broken_if_no_context_used
    assert instance1.expensive_instance is instance2.expensive_instance
AssertionError
```

**Comment by nachtmaar** [comment]
Moreover, in your singleton example in README.md your missing the `inject` import.

```from serum import singleton``` ->```from serum import singleton, inject```

**Comment by suned** [comment]
Nice catch! I might be able to squeeze in some time this week to fix this 🤓

**Comment by nachtmaar** [comment]
Nice to hear. Am looking forward to ingrate serum into my code if fixed :)

**Comment by suned** [comment]
Sorry about the long delay. Was tied up with my day job 💸 
Fixed in https://pypi.org/project/serum/5.1.0/
