### ISSUE TITLE
Initialize classes with __init__ arguments

### ISSUE THREAD

**Issue by JosXa** [suned/serum#27]
> serum assumes that the __init__ method of dependency decorated classes can be called without any arguments. This means that all arguments to __init__ of dependency decorated classes must be injected using inject.

How would you go about instantiating a complex object that requires a number of initialization arguments (primitive strings, ints, etc.), while still having it be injectable? An example use case would be a random API-consuming `Client`  from a third-party library that expects you to pass api tokens, api hashes, session paths etc.
I guess you could instantiate such an object yourself, but then how would you make Serum aware of the instance? And I suppose this would also defeat the purpose of DI. 
Maybe I have failed to understand the use of `Contexts`, as they seem to be related. Any hints?

**Comment by suned** [comment]
You could do one of two things: wrap the library class in a dependency decorated class, or decorate the class itself.
Say that you have a class called `Client` from a third party library that expects an argument `api_token` in its init method.

Then option one would look like

```python
@dependency
@inject
class InjectableClient
    api_token: str

    def __init__(self):
        self._client = Client(api_token=self.api_token)
    
def __getattr__(self, name):
        return getattr(self._client, name)
```

Option 2 would look like:

```python
InjectableClient = dependency(Client)
InjectableClient.__init__ = inject(InjectableClient.__init__)
```

In both cases you would supply the `api_token` with a `Context`:
```python
@inject
def needs_client(client: InjectableClient):
    client.method()

with Context(api_token='my_token'):
    needs_client()
```

But more appropriately, I think you should just supply the client as a named dependency: instead of trying to inject the api token, just inject the whole `Client`!

```python
@inject
def needs_client(client: Client):
    client.method()

with Context(client=Client(api_token='my_token'):
    needs_client()
```

I guess this is what you meant by:

> I guess you could instantiate such an object yourself, but then how would you make Serum aware of the instance? And I suppose this would also defeat the purpose of DI.

I dont think this defeats the purpose of DI at all. The main value proposition of DI is that you don't have to wire your application yourself. Say that the method `needs_client` was somewhere far from your programs entry point. If you did 'manual' DI you would have to instantiate the object at the entry point and thread it through every function call so that you could eventually pass it to `needs_client`. What `serum` (and DI libraries in general) allows you to do is to setup your dependencies once, and then have the library take care of the wiring for you.

**Comment by JosXa** [comment]
Thanks a lot for your exhaustive answer. I will try this out and report back should more questions arise, but what you say makes a lot of sense and definitely solved my problem 👍

**Comment by shazz** [comment]
Hi,

I tried to implement your last solution but doesn't work as expected, can you tell me what I did wrong ?
Looks like the `repo=` in the Context is not used...

````python
# pip install serum
from serum import inject, dependency, Context

# -------------------------------------------------------- #

@dependency
class AbstractRepo:

    @inject
    def __init__(self, connection_string: str) -> None:
        self.connection_string = connection_string

    def get_data(self, query: str) -> str:
        raise NotImplementedError()

class DBRepo(AbstractRepo):

    def get_data(self, query: str):
        print("you got data!")  

# -------------------------------------------------------- #
        
@inject  # Dependencies are injected using a class decorator...
class DataService:
    repo: AbstractRepo      # ...and class level annotations...
    repo_source: str        # class level annotations annotated with a type that is not
                            # decorated with 'dependency' will be treated as a named dependency

# Contexts provide dependencies
with Context(repo=DBRepo(connection_string="test"), repo_source="influxDB"):
    print(type(DataService().repo))
    print(DataService().repo_source)

````

````
Traceback (most recent call last):
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_context.py", line 232, in instantiate
    component_instance = instance(dependency_type)
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_context.py", line 214, in instance
    component_instance = component_type()
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_inject.py", line 144, in decorator
    return f(*args, **dependency_args)
TypeError: __init__() missing 1 required positional argument: 'connection_string'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inject_construct.py", line 31, in <module>
    print(type(DataService().repo))
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_injected_dependency.py", line 14, in __get__
    raise dependency_instance
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_inject.py", line 30, in __set_dependency
    instance = provide(configuration)
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_context.py", line 295, in provide
    return Context.provide(configuration)
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_context.py", line 248, in provide
    return instantiate(dependency)
  File "C:\Work\Analytics\git\ESP\test\.venv\lib\site-packages\serum\_context.py", line 240, in instantiate
    ) from e
serum.exceptions.InjectionError: Could not instantiate <class '__main__.AbstractRepo'> when injecting "repo" in <__main__.DataService object at 0x036A1B50>.

````

**Comment by shazz** [comment]
Ok found the solution:
````python
with Context(DBRepo, connection_string="test", repo_source="influxDB"):
````
